.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vritzcoin_qt test_vritzcoin_qt
clean: FORCE
	$(MAKE) -C .. vritzcoin_qt_clean test_vritzcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_vritzcoin_qt_check
vritzcoin-qt vritzcoin-qt.exe: FORCE
	 $(MAKE) -C .. vritzcoin_qt
